import type { WidenLeaves } from "@vireocodedev/localization";
import type itemEn from "./item.en";

const itemHr = {
  title: "Stavka",
  fields: {
    name: "Naziv",
    description: "Opis",
    quantity: "Količina",
    status: "Status",
  },
  status: {
    DRAFT: "Skica",
    ACTIVE: "Aktivno",
    ARCHIVED: "Arhivirano",
  },
  validation: {
    name: { min: "Unesite najmanje {{minimum}} znaka." },
    description: { max: "Upotrijebite najviše 2.000 znakova." },
    quantity: {
      integer: "Upotrijebite cijeli broj.",
      nonnegative: "Količina ne može biti negativna.",
    },
  },
  form: {
    section: "Detalji stavke",
    description: "Polja u nastavku sprema Spring Boot API.",
    create: "Kreiraj stavku",
    update: "Spremi promjene",
    createTitle: "Kreiraj stavku",
    updateTitle: "Uredi stavku",
    close: "Zatvori obrazac stavke",
    notProvided: "Nije navedeno",
    namePlaceholder: "Revizija sustava dizajna",
    descriptionPlaceholder: "Što je potrebno napraviti?",
  },
  table: {
    item: "Stavka",
    noDescription: "Nema opisa",
    pending: "Na čekanju",
    conflict: "Sukob",
    resolveConflict: "Riješi sukob sinkronizacije",
    resolveConflictAria: "Riješi sukob sinkronizacije za {{name}}",
    actions: "Radnje",
    history: "Povijest stavke",
    historyOffline: "Povijest je dostupna kada je aplikacija povezana.",
    historyAria: "Povijest",
    edit: "Uredi stavku",
    editAria: "Uredi",
    delete: "Izbriši stavku",
    deleteAria: "Izbriši",
  },
  history: {
    title: "Povijest · {{name}}",
    close: "Zatvori povijest stavke",
    loading: "Učitavanje povijesti stavke",
    retry: "Pokušaj ponovno",
    loadError: "Povijest stavke nije se mogla učitati.",
    staleError: "Povijest nije moguće osvježiti. Prikazuje se posljednja spremljena kopija.",
    empty: "Za ovu stavku nije zabilježena povijest.",
    description: "Zabilježene promjene prikazane su kronološkim redoslijedom.",
    entryAria: "Zapis povijesti za {{name}}",
    systemActor: "Sustav",
    labels: {
      expandSection: "Proširi odjeljak",
      collapseSection: "Sažmi odjeljak",
      showUnchanged: "Prikaži nepromijenjeno",
      hideUnchanged: "Sakrij nepromijenjeno",
      showMore: "Prikaži više",
      showLess: "Prikaži manje",
      added: "Dodano",
      removed: "Uklonjeno",
      updated: "Ažurirano",
      moved: "Premješteno",
      unchanged: "Nepromijenjeno",
      field: "Polje",
      previous: "Prethodno",
      current: "Trenutačno",
      value: "Vrijednost",
      notPresent: "Nije prisutno",
      change: "{{count}} promjena",
      changes: "{{count}} promjena",
    },
  },
  messages: {
    queued: "Stavka {{name}} je stavljena u red za sinkronizaciju",
    synchronized_one: "Sinkronizirana je {{count}} promjena na čekanju.",
    synchronized_few: "Sinkronizirane su {{count}} promjene na čekanju.",
    synchronized_other: "Sinkronizirano je {{count}} promjena na čekanju.",
    created: "Stavka {{name}} je kreirana",
    createFailed: "Stavku nije moguće kreirati.",
    updated: "Stavka {{name}} je ažurirana",
    updateFailed: "Stavku nije moguće ažurirati.",
    deleted: "Stavka {{name}} je izbrisana",
    deleteFailed: "Stavku nije moguće izbrisati.",
  },
} satisfies WidenLeaves<typeof itemEn>;

export default itemHr;
