const itemEn = {
  title: "Item",
  fields: {
    name: "Name",
    description: "Description",
    quantity: "Quantity",
    status: "Status",
  },
  status: {
    DRAFT: "Draft",
    ACTIVE: "Active",
    ARCHIVED: "Archived",
  },
  validation: {
    name: { min: "Enter at least {{minimum}} characters." },
    description: { max: "Use at most 2,000 characters." },
    quantity: {
      integer: "Use a whole number.",
      nonnegative: "Quantity cannot be negative.",
    },
  },
  form: {
    section: "Item details",
    description: "The fields below are persisted by the Spring Boot API.",
    create: "Create item",
    update: "Save changes",
    createTitle: "Create item",
    updateTitle: "Edit item",
    close: "Close item form",
    notProvided: "Not provided",
    namePlaceholder: "Design system audit",
    descriptionPlaceholder: "What needs to be done?",
  },
  table: {
    item: "Item",
    noDescription: "No description",
    pending: "Pending",
    conflict: "Conflict",
    actions: "Actions",
    history: "Item history",
    historyOffline: "History is available when the app is online.",
    historyAria: "History",
    edit: "Edit item",
    editAria: "Edit",
    delete: "Delete item",
    deleteAria: "Delete",
  },
  history: {
    title: "History · {{name}}",
    close: "Close item history",
    loading: "Loading item history",
    retry: "Retry",
    loadError: "Item history could not be loaded.",
    staleError: "History could not be refreshed. Showing the most recent saved copy.",
    empty: "No history has been recorded for this item.",
    description: "Recorded changes are shown in chronological order.",
    entryAria: "History entry for {{name}}",
    systemActor: "System",
    labels: {
      expandSection: "Expand section",
      collapseSection: "Collapse section",
      showUnchanged: "Show unchanged",
      hideUnchanged: "Hide unchanged",
      showMore: "Show more",
      showLess: "Show less",
      added: "Added",
      removed: "Removed",
      updated: "Updated",
      moved: "Moved",
      unchanged: "Unchanged",
      field: "Field",
      previous: "Previous",
      current: "Current",
      value: "Value",
      notPresent: "Not present",
      change: "{{count}} change",
      changes: "{{count}} changes",
    },
  },
  messages: {
    queued: "{{name}} queued for synchronization",
    synchronized_one: "{{count}} queued change synchronized.",
    synchronized_few: "{{count}} queued changes synchronized.",
    synchronized_other: "{{count}} queued changes synchronized.",
    created: "{{name}} created",
    createFailed: "Item could not be created.",
    updated: "{{name}} updated",
    updateFailed: "Item could not be updated.",
    deleted: "{{name}} deleted",
    deleteFailed: "Item could not be deleted.",
  },
} as const;

export default itemEn;
