const en = {
  offline: {
    ONLINE: "Online",
    OFFLINE: "Offline",
    SYNCING: "Syncing",
    PENDING: "{{count}} pending",
    FAILED: "{{count}} failed",
    OPEN_SETTINGS: "Open offline settings",
    CONNECTION_RESTORED: "Connection restored.",
    WORKING_OFFLINE: "Working offline.",
  },
  navigation: {
    PRIMARY: "Primary navigation",
    OVERVIEW: "Overview",
    ITEMS: "Items",
    SETTINGS: "Settings",
    EXPAND: "Expand navigation",
    COMPACT: "Compact navigation",
    CLOSE: "Close navigation",
    OPEN: "Open navigation",
    QUICK: "Quick navigation",
  },
  account: {
    LABEL: "Account",
    OPEN_MENU: "Open account menu",
    SIGN_OUT: "Sign out",
    SIGN_OUT_PENDING_TITLE: "Discard offline changes and sign out?",
    SIGN_OUT_PENDING_MESSAGE: "Signing out removes {{count}} queued or failed changes from this device.",
  },
  auth: {
    outcomes: {
      unauthenticated: "Sign in to continue.",
      invalidCredentials: "The username or password is incorrect.",
      forbidden: "Your account is not allowed to access this workspace.",
      expiredSession: "Your session expired. Sign in again.",
      offline: "The sign-in service cannot be reached. Check your connection and try again.",
      server: "The sign-in service is temporarily unavailable. Try again later.",
      malformedResponse: "The sign-in service returned an unexpected response. Try again or contact support.",
      logoutFailure: "Sign out could not be completed. You are still signed in; please try again.",
    },
  },
  actions: { BACK: "Back" },
  loading: { application: "Loading application", page: "Loading page" },
  errorBoundary: {
    heading: "Something went wrong",
    message: "This page could not be displayed. Try again, or use one of the recovery actions below.",
    actions: "Application recovery actions",
    retry: "Try again",
    home: "Go home",
    reload: "Reload application",
    signOut: "Sign out",
  },
  session: { expired: "Your session expired. Sign in again." },
  pwa: {
    later: "Later",
    offlineReady: "The app shell is ready for limited offline use. Server data still requires a connection.",
    registrationUnavailable:
      "Offline support could not be enabled. Reload the page or contact support if this persists.",
    update: "Update",
    updateReady: "A new version is ready.",
    updateUnavailable: "The update could not be applied. Keep working, then reload when it is safe.",
  },
  unsavedChanges: {
    title: "Discard unsaved changes?",
    message: "Your changes will be lost if you close this form.",
    keepEditing: "Keep editing",
    discard: "Discard changes",
  },
} as const;

export default en;
