import { AppAxiosHttpClient, postAppPagedSearch } from "@/app/data/network/clients/AppAxiosClient";
import type { ItemApi, ItemFilters, ItemRequestOptions } from "./item.api";
import { Item, ItemTransport, toCompleteItemPatchRequest, toItemCreateRequest } from "../models/Item";
import type { PageableParams } from "@vireocodedev/infrastructure";
import { z } from "zod";
import { APP_QUERY_ENTITY } from "@/app/data/query/models/AppQueryEntityKey";
import { serializeQueryFilterDocument } from "@/app/data/query/models/QueryFilterDocument";
import { createAdapterSlot } from "@/app/adapters/createAdapterSlot";

export class ItemApiOnline extends AppAxiosHttpClient implements ItemApi {
  constructor() {
    super("items");
  }

  async search(pageable: PageableParams, { searchText, queryFilters }: ItemFilters, request?: ItemRequestOptions) {
    const page = await searchItemTransport(pageable, { searchText, queryFilters }, request);
    return { ...page, content: page.content.map(item => Item.parse(item)) };
  }

  async create(value: Item) {
    // Item IDs are generated by the client so an offline create can be replayed idempotently.
    const created = await this.httpPost(Item)("", toItemCreateRequest(value));
    return { persistence: "SAVED" as const, value: created };
  }

  async update(id: string, value: Item) {
    const updated = await this.httpPatch(Item)(id, toCompleteItemPatchRequest(value));
    return { persistence: "SAVED" as const, value: updated };
  }

  async delete(id: string, version: number) {
    await this.httpDelete(z.unknown())(id, { data: { version } });
    return { persistence: "SAVED" as const, value: undefined };
  }
}

export function searchItemTransport(
  pageable: PageableParams,
  { searchText, queryFilters }: ItemFilters,
  request?: ItemRequestOptions,
) {
  return postAppPagedSearch({
    endpointName: "items",
    schema: ItemTransport,
    pageable,
    filters: {
      searchText,
      queryFiltersJson: serializeQueryFilterDocument(queryFilters, APP_QUERY_ENTITY.item),
    },
    config: { signal: request?.signal },
  });
}

const itemApiSlot = createAdapterSlot<ItemApi>(new ItemApiOnline());

export const itemApi = itemApiSlot.adapter;
export const configureItemApi = itemApiSlot.configure;
